/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReglementationCinematographiqueRouteImport } from './routes/reglementation-cinematographique'
import { Route as OrganisationRouteImport } from './routes/organisation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as DirectionsCinematographieProductionsAudiovisuellesRouteImport } from './routes/directions/cinematographie-productions-audiovisuelles'

const ReglementationCinematographiqueRoute =
  ReglementationCinematographiqueRouteImport.update({
    id: '/reglementation-cinematographique',
    path: '/reglementation-cinematographique',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganisationRoute = OrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsCinematographieProductionsAudiovisuellesRoute =
  DirectionsCinematographieProductionsAudiovisuellesRouteImport.update({
    id: '/directions/cinematographie-productions-audiovisuelles',
    path: '/directions/cinematographie-productions-audiovisuelles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organisation': typeof OrganisationRoute
  '/reglementation-cinematographique': typeof ReglementationCinematographiqueRoute
  '/directions/cinematographie-productions-audiovisuelles': typeof DirectionsCinematographieProductionsAudiovisuellesRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organisation': typeof OrganisationRoute
  '/reglementation-cinematographique': typeof ReglementationCinematographiqueRoute
  '/directions/cinematographie-productions-audiovisuelles': typeof DirectionsCinematographieProductionsAudiovisuellesRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organisation': typeof OrganisationRoute
  '/reglementation-cinematographique': typeof ReglementationCinematographiqueRoute
  '/directions/cinematographie-productions-audiovisuelles': typeof DirectionsCinematographieProductionsAudiovisuellesRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organisation'
    | '/reglementation-cinematographique'
    | '/directions/cinematographie-productions-audiovisuelles'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organisation'
    | '/reglementation-cinematographique'
    | '/directions/cinematographie-productions-audiovisuelles'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/organisation'
    | '/reglementation-cinematographique'
    | '/directions/cinematographie-productions-audiovisuelles'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganisationRoute: typeof OrganisationRoute
  ReglementationCinematographiqueRoute: typeof ReglementationCinematographiqueRoute
  DirectionsCinematographieProductionsAudiovisuellesRoute: typeof DirectionsCinematographieProductionsAudiovisuellesRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reglementation-cinematographique': {
      id: '/reglementation-cinematographique'
      path: '/reglementation-cinematographique'
      fullPath: '/reglementation-cinematographique'
      preLoaderRoute: typeof ReglementationCinematographiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation': {
      id: '/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof OrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions/cinematographie-productions-audiovisuelles': {
      id: '/directions/cinematographie-productions-audiovisuelles'
      path: '/directions/cinematographie-productions-audiovisuelles'
      fullPath: '/directions/cinematographie-productions-audiovisuelles'
      preLoaderRoute: typeof DirectionsCinematographieProductionsAudiovisuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganisationRoute: OrganisationRoute,
  ReglementationCinematographiqueRoute: ReglementationCinematographiqueRoute,
  DirectionsCinematographieProductionsAudiovisuellesRoute:
    DirectionsCinematographieProductionsAudiovisuellesRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
